//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prova_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comments()
        {
            this.comments1 = new HashSet<comments>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
        public string comment { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> picture_id { get; set; }
        public Nullable<int> parent_comment_id { get; set; }
        public Nullable<int> position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments1 { get; set; }
        public virtual comments comments2 { get; set; }
        public virtual pictures pictures { get; set; }
        public virtual user user { get; set; }
    }
}
