//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prova_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> picture_id { get; set; }
        public byte[] data { get; set; }
        public string comment { get; set; }
    
        public virtual pictures pictures { get; set; }
        public virtual user user { get; set; }
    }
}
